### ISSUE TITLE
The eigenVectors seem not to be well calculated

### ISSUE THREAD

**Issue by khayyam90** [jbrown1618/vector#125]
Hello,
I have tried to compute the eigen vector & values and I am facing the following issue : 
`let m = mat([
        [1,0,0],
        [0,2,0],
        [0,0,3]
]);
let e = eig(m);

At runtime in my browser I get a "Uncaught Error: Unexpected error: unable to find a solution to the eigenvector equation".
Did I something wrong ?

**Comment by jbrown1618** [comment]
Sorry for taking so long to notice this - I haven't been keeping an eye on the project. I've reproduced the issue in a unit test and will get to it shortly.

**Comment by jbrown1618** [comment]
Yikes - the bug is actually in the backward substitution code - it is not handling certain classes of underdetermined systems correctly. This is particularly a problem for eigenvector finding.

**Comment by jbrown1618** [comment]
@khayyam90 This is fixed in version 4.0.0
