### ISSUE TITLE
Does not calculate eigenvalues for singular matrices

### ISSUE THREAD

**Issue by khayyam90** [jbrown1618/vector#129]
Hi,

It's me again, still with the eigen vector calculation. 
I have another case ending with an error : 
```
let m = mat([
        [2,-1,-1],
        [-1,2,-1],
        [-1,-1,2]
        ]);
        let e = eig(m);
```

Uncaught Error: A is singular; no QR decomposition exists
but the eigen values do exist : 3,3,0

**Comment by jbrown1618** [comment]
That is helpful - I'm using the QR algorithm to find the eigenvalues, but my implementation chokes on singular matrices.

**Comment by jbrown1618** [comment]
The right solution is, I think, to fix my QR algorithm implementation (rather than try a different method when it fails). The QR factorization exists for singular matrices (but the result is not unique).

**Comment by jbrown1618** [comment]
It might be necessary to use an algorithm other than Graham-Schmidt for the QR decomposition.
